/*
 * Word banks for the crossword game.
 * Each theme has three difficulty levels: easy, medium, tricky.
 * Every entry is { a: ANSWER, c: "clue" }.
 * Answers are single words, letters A-Z only, lengths kept friendly for kids.
 *
 * Difficulty guide (grade 6 and below):
 *   easy   -> short words (3-5 letters), very direct clues
 *   medium -> medium words (4-7 letters), slightly playful clues
 *   tricky -> longer words (5-9 letters), riddle-style / "tricky" clues
 */

const THEMES = {
  regular: {
    name: "Everyday",
    emoji: "✏️",
    blurb: "Classic words from school and home.",
    levels: {
      easy: [
        { a: "CAT", c: "A pet that says meow" },
        { a: "DOG", c: "A pet that barks" },
        { a: "SUN", c: "It lights up the daytime sky" },
        { a: "BALL", c: "A round toy you bounce or kick" },
        { a: "BOOK", c: "You read this" },
        { a: "TREE", c: "It has a trunk, branches, and leaves" },
        { a: "FISH", c: "It swims and has fins" },
        { a: "MILK", c: "A white drink from cows" },
        { a: "RAIN", c: "Water that falls from clouds" },
        { a: "STAR", c: "It twinkles in the night sky" },
        { a: "BIRD", c: "An animal with feathers that can fly" },
        { a: "CAKE", c: "A sweet treat for birthdays" },
      ],
      medium: [
        { a: "PENCIL", c: "You write with this and can erase it" },
        { a: "GARDEN", c: "A place where flowers and veggies grow" },
        { a: "WINDOW", c: "Glass you look through in a wall" },
        { a: "BASKET", c: "You carry fruit or laundry in it" },
        { a: "PLANET", c: "Earth is one of these in space" },
        { a: "BRIDGE", c: "You cross this over a river" },
        { a: "ORANGE", c: "A round fruit and also a color" },
        { a: "FRIEND", c: "Someone you like to play with" },
        { a: "ROCKET", c: "It blasts off into space" },
        { a: "TURTLE", c: "A slow animal with a hard shell" },
        { a: "PUZZLE", c: "Pieces you fit together for fun" },
        { a: "BUTTON", c: "You press this or it holds a shirt closed" },
      ],
      tricky: [
        { a: "RAINBOW", c: "Seven colors that appear after a storm" },
        { a: "LIBRARY", c: "A quiet place full of books to borrow" },
        { a: "DIAMOND", c: "A sparkly gem and a baseball field shape" },
        { a: "VOLCANO", c: "A mountain that can erupt with hot lava" },
        { a: "PENGUIN", c: "A bird in a tuxedo that cannot fly" },
        { a: "COMPASS", c: "It always points you toward north" },
        { a: "GRAVITY", c: "The force that pulls things down to Earth" },
        { a: "TRIANGLE", c: "A shape with three sides" },
        { a: "TREASURE", c: "Gold and jewels a pirate hides" },
        { a: "WHISPER", c: "To talk very, very quietly" },
        { a: "JOURNEY", c: "A long trip from one place to another" },
        { a: "MYSTERY", c: "A puzzle or secret to be solved" },
      ],
    },
  },

  halloween: {
    name: "Halloween",
    emoji: "🎃",
    blurb: "Spooky words for a frightfully fun puzzle!",
    levels: {
      easy: [
        { a: "BAT", c: "A flying animal seen at night" },
        { a: "OWL", c: "A bird that hoots in the dark" },
        { a: "BOO", c: "What a ghost says to scare you" },
        { a: "CAT", c: "A black one is a Halloween symbol" },
        { a: "WEB", c: "A spider spins this sticky trap" },
        { a: "BONE", c: "A skeleton is made of these" },
        { a: "MASK", c: "You wear this to hide your face" },
        { a: "MOON", c: "It glows full and bright on spooky nights" },
        { a: "CANDY", c: "Sweet treats you collect on Halloween" },
        { a: "DARK", c: "The opposite of light" },
        { a: "FANG", c: "A pointy tooth a vampire has" },
        { a: "TOMB", c: "A stone box where the dead rest" },
      ],
      medium: [
        { a: "GHOST", c: "A see-through spirit that goes 'boo'" },
        { a: "WITCH", c: "She flies on a broom and casts spells" },
        { a: "SPIDER", c: "An eight-legged web spinner" },
        { a: "GOBLIN", c: "A small, mischievous monster" },
        { a: "BROOM", c: "A witch's flying ride" },
        { a: "POTION", c: "A magic drink in a bubbling pot" },
        { a: "SPOOKY", c: "Another word for creepy or scary" },
        { a: "PUMPKIN", c: "An orange gourd you carve into a face" },
        { a: "COSTUME", c: "The outfit you wear to dress up" },
        { a: "SHADOW", c: "A dark shape that follows you" },
        { a: "CACKLE", c: "A witch's spooky laugh" },
        { a: "HAUNT", c: "What a ghost does to a house" },
      ],
      tricky: [
        { a: "SKELETON", c: "A spooky frame of bones with no skin" },
        { a: "VAMPIRE", c: "A creature with fangs who fears garlic" },
        { a: "MONSTER", c: "A scary creature that might hide under the bed" },
        { a: "MUMMY", c: "An ancient body wrapped in bandages" },
        { a: "CAULDRON", c: "The big black pot a witch stirs" },
        { a: "GRAVEYARD", c: "A field full of tombstones" },
        { a: "MIDNIGHT", c: "Twelve o'clock, the witching hour" },
        { a: "LANTERN", c: "A carved pumpkin with a glowing light, jack-o-___" },
        { a: "SHRIEK", c: "A loud, scary scream" },
        { a: "ZOMBIE", c: "An undead creature that groans and shuffles" },
        { a: "PHANTOM", c: "A fancy word for a ghost" },
        { a: "WEREWOLF", c: "A person who turns furry under a full moon" },
      ],
    },
  },

  valentines: {
    name: "Valentine's Day",
    emoji: "💝",
    blurb: "Sweet and lovely words full of heart.",
    levels: {
      easy: [
        { a: "LOVE", c: "A warm feeling for someone special" },
        { a: "HUG", c: "You wrap your arms around someone for this" },
        { a: "KISS", c: "A little peck to show you care" },
        { a: "ROSE", c: "A red flower for Valentine's Day" },
        { a: "PINK", c: "A soft color, mix of red and white" },
        { a: "CARD", c: "You send this with a sweet message" },
        { a: "CUTE", c: "Adorable and sweet" },
        { a: "GIFT", c: "A present you give with love" },
        { a: "DOVE", c: "A white bird of peace and love" },
        { a: "BEAR", c: "A stuffed teddy ___ makes a sweet gift" },
        { a: "DEAR", c: "A loving way to start a letter" },
        { a: "STAR", c: "You're my shining ___" },
      ],
      medium: [
        { a: "HEART", c: "The shape that means love" },
        { a: "CUPID", c: "The baby angel who shoots love arrows" },
        { a: "ARROW", c: "Cupid shoots this from his bow" },
        { a: "FLOWER", c: "A bloom you give to someone special" },
        { a: "CANDY", c: "Sweet treats in a heart-shaped box" },
        { a: "FRIEND", c: "Someone you share your heart with" },
        { a: "SWEET", c: "Like sugar, or a kind person" },
        { a: "RIBBON", c: "A pretty bow on a gift" },
        { a: "LETTER", c: "A note you mail to someone you love" },
        { a: "PETALS", c: "The soft colorful parts of a flower" },
        { a: "CHERISH", c: "To love and hold dear" },
        { a: "ADMIRE", c: "To really like and look up to someone" },
      ],
      tricky: [
        { a: "CHOCOLATE", c: "A sweet brown treat often given in a heart box" },
        { a: "ROMANCE", c: "A sweet, loving story or feeling" },
        { a: "AFFECTION", c: "A gentle feeling of fondness and love" },
        { a: "SWEETHEART", c: "A loving name for the one you adore" },
        { a: "DEVOTION", c: "Deep, loyal love for someone" },
        { a: "CHARMING", c: "Pleasant and delightful, like a prince" },
        { a: "BOUQUET", c: "A bunch of flowers tied together" },
        { a: "TENDER", c: "Soft, gentle, and caring" },
        { a: "PROMISE", c: "A word you give that you will keep" },
        { a: "CARNATION", c: "A frilly flower often given on this day" },
        { a: "FOREVER", c: "For all time, with no end" },
        { a: "DELIGHT", c: "A feeling of great joy and happiness" },
      ],
    },
  },

  christmas: {
    name: "Christmas",
    emoji: "🎄",
    blurb: "Jolly, snowy words for the holidays.",
    levels: {
      easy: [
        { a: "ELF", c: "Santa's little helper" },
        { a: "TOY", c: "A gift a child loves to play with" },
        { a: "STAR", c: "It sits on top of the tree" },
        { a: "BELL", c: "It jingles and rings" },
        { a: "SNOW", c: "White flakes that fall in winter" },
        { a: "GIFT", c: "A wrapped present under the tree" },
        { a: "TREE", c: "You decorate this green plant for Christmas" },
        { a: "SLED", c: "You ride this down a snowy hill" },
        { a: "SANTA", c: "The jolly man in a red suit" },
        { a: "RED", c: "Santa's favorite color to wear" },
        { a: "CANE", c: "A candy ___ is striped and sweet" },
        { a: "GOLD", c: "A shiny color of tinsel and gifts" },
      ],
      medium: [
        { a: "REINDEER", c: "Animals that pull Santa's sleigh" },
        { a: "SLEIGH", c: "Santa's flying ride" },
        { a: "FROSTY", c: "The name of a famous snowman" },
        { a: "WREATH", c: "A round decoration for the front door" },
        { a: "CANDLE", c: "A small flame that glows on cold nights" },
        { a: "WINTER", c: "The cold, snowy season" },
        { a: "JINGLE", c: "The sound of ringing bells" },
        { a: "RIBBON", c: "It ties up a pretty present" },
        { a: "COOKIE", c: "A treat left out for Santa" },
        { a: "MITTEN", c: "It keeps your hand warm in the snow" },
        { a: "STOCKING", c: "A sock hung by the fireplace for gifts" },
        { a: "HOLLY", c: "A plant with red berries and green leaves" },
      ],
      tricky: [
        { a: "SNOWFLAKE", c: "No two of these icy crystals are alike" },
        { a: "ORNAMENT", c: "A shiny ball that hangs on the tree" },
        { a: "CHIMNEY", c: "Santa slides down this to enter your home" },
        { a: "RUDOLPH", c: "The reindeer with a glowing red nose" },
        { a: "GINGERBREAD", c: "A spicy cookie shaped like a little man" },
        { a: "MISTLETOE", c: "A plant you might get a kiss under" },
        { a: "NUTCRACKER", c: "A toy soldier that cracks open nuts" },
        { a: "BLIZZARD", c: "A heavy snowstorm with strong wind" },
        { a: "CAROL", c: "A happy Christmas song" },
        { a: "TINSEL", c: "Shiny strands draped on the tree" },
        { a: "POINSETTIA", c: "A famous red Christmas flower" },
        { a: "NAUGHTY", c: "The opposite of nice on Santa's list" },
      ],
    },
  },

  space: {
    name: "Outer Space",
    emoji: "🚀",
    blurb: "Blast off with words from the galaxy!",
    levels: {
      easy: [
        { a: "SUN", c: "The star at the center of our system" },
        { a: "MOON", c: "It orbits Earth and glows at night" },
        { a: "STAR", c: "A glowing ball of gas in the sky" },
        { a: "MARS", c: "The red planet" },
        { a: "ALIEN", c: "A creature from another planet" },
        { a: "ORBIT", c: "The path a planet travels around the sun" },
        { a: "COMET", c: "A space snowball with a glowing tail" },
        { a: "EARTH", c: "The planet we all live on" },
        { a: "ROCK", c: "Space ones are called meteors" },
        { a: "DARK", c: "How space looks with no light" },
        { a: "GLOW", c: "What stars do in the night sky" },
        { a: "RAYS", c: "Beams of light from the sun" },
      ],
      medium: [
        { a: "PLANET", c: "Jupiter and Saturn are both this" },
        { a: "ROCKET", c: "A ship that launches into space" },
        { a: "GALAXY", c: "A huge group of millions of stars" },
        { a: "SATURN", c: "The planet famous for its rings" },
        { a: "METEOR", c: "A shooting star streaking across the sky" },
        { a: "JUPITER", c: "The biggest planet in our solar system" },
        { a: "GRAVITY", c: "The force that keeps planets in orbit" },
        { a: "ECLIPSE", c: "When the moon blocks out the sun" },
        { a: "CRATER", c: "A bowl-shaped dent on the moon" },
        { a: "NEPTUNE", c: "The farthest planet, deep blue in color" },
        { a: "VENUS", c: "The hottest planet, second from the sun" },
        { a: "COMET", c: "It zooms by with an icy, glowing tail" },
      ],
      tricky: [
        { a: "ASTRONAUT", c: "A person trained to travel in space" },
        { a: "TELESCOPE", c: "A tool that makes far-away stars look close" },
        { a: "SATELLITE", c: "A machine that orbits Earth, like the moon" },
        { a: "UNIVERSE", c: "Everything that exists, all of space" },
        { a: "ASTEROID", c: "A small rocky body orbiting the sun" },
        { a: "NEBULA", c: "A colorful cloud of gas and dust in space" },
        { a: "SPACESHIP", c: "A vehicle that carries crew through the stars" },
        { a: "GALILEO", c: "Famous scientist who studied the stars with a telescope" },
        { a: "MERCURY", c: "The smallest planet, closest to the sun" },
        { a: "LAUNCH", c: "The moment a rocket lifts off" },
        { a: "STARGAZE", c: "To look up and admire the night sky" },
        { a: "SOLAR", c: "Having to do with the sun, like a ___ system" },
      ],
    },
  },

  ocean: {
    name: "Under the Sea",
    emoji: "🐠",
    blurb: "Dive into a sea of watery words.",
    levels: {
      easy: [
        { a: "FISH", c: "It swims with fins and gills" },
        { a: "CRAB", c: "It walks sideways and has claws" },
        { a: "WAVE", c: "Water that rolls onto the beach" },
        { a: "SAND", c: "Tiny grains on the beach" },
        { a: "SEAL", c: "A sea animal that claps and barks" },
        { a: "SHELL", c: "A hard home a snail or clam carries" },
        { a: "REEF", c: "A colorful coral home for fish" },
        { a: "SWIM", c: "To move through the water" },
        { a: "BOAT", c: "It floats on top of the water" },
        { a: "DEEP", c: "Very far down in the ocean" },
        { a: "SALT", c: "It makes the ocean water taste this way" },
        { a: "TIDE", c: "The rise and fall of the sea" },
      ],
      medium: [
        { a: "SHARK", c: "A big fish with rows of sharp teeth" },
        { a: "WHALE", c: "The largest animal in the ocean" },
        { a: "CORAL", c: "Colorful rock-like reef made by tiny animals" },
        { a: "OCTOPUS", c: "A sea creature with eight arms" },
        { a: "DOLPHIN", c: "A smart, playful animal that leaps from waves" },
        { a: "LOBSTER", c: "A sea animal with big claws, turns red when cooked" },
        { a: "ISLAND", c: "Land with water all around it" },
        { a: "ANCHOR", c: "It drops down to keep a boat in place" },
        { a: "SEAWEED", c: "Green plants that float in the sea" },
        { a: "STARFISH", c: "A sea creature shaped like a star" },
        { a: "PEARL", c: "A shiny ball that forms inside an oyster" },
        { a: "CURRENT", c: "A flow of moving water in the sea" },
      ],
      tricky: [
        { a: "JELLYFISH", c: "A see-through sea creature that can sting" },
        { a: "SUBMARINE", c: "A ship that travels underwater" },
        { a: "SEAHORSE", c: "A tiny fish shaped like a horse's head" },
        { a: "TREASURE", c: "Sunken gold a diver might find" },
        { a: "STINGRAY", c: "A flat fish that glides like it's flying" },
        { a: "BARNACLE", c: "A little shell creature stuck to rocks and boats" },
        { a: "PLANKTON", c: "Tiny drifting food that whales love to eat" },
        { a: "LIGHTHOUSE", c: "A tall tower that warns ships with its light" },
        { a: "TENTACLE", c: "A long bendy arm of an octopus or squid" },
        { a: "MERMAID", c: "A make-believe creature, half girl half fish" },
        { a: "SEASHELL", c: "You can hear the ocean when you hold it to your ear" },
        { a: "SNORKEL", c: "A tube that lets you breathe while face-down in water" },
      ],
    },
  },

  jungle: {
    name: "Jungle Safari",
    emoji: "🦁",
    blurb: "Wild words from the rainforest and savanna.",
    levels: {
      easy: [
        { a: "LION", c: "The king of the jungle" },
        { a: "APE", c: "A big animal like a gorilla, no tail" },
        { a: "FROG", c: "A green hopper that says ribbit" },
        { a: "VINE", c: "A long plant Tarzan swings on" },
        { a: "BIRD", c: "A colorful one might be a parrot" },
        { a: "ZEBRA", c: "A striped animal like a wild horse" },
        { a: "BUG", c: "A tiny crawly insect" },
        { a: "TREE", c: "Monkeys love to climb these" },
        { a: "ROAR", c: "The loud sound a lion makes" },
        { a: "TAIL", c: "A monkey hangs by this" },
        { a: "MUD", c: "Wet dirt a pig loves to roll in" },
        { a: "LEAF", c: "A flat green part of a plant" },
      ],
      medium: [
        { a: "TIGER", c: "A big orange cat with black stripes" },
        { a: "MONKEY", c: "A playful animal that swings through trees" },
        { a: "PARROT", c: "A colorful bird that can copy your words" },
        { a: "JAGUAR", c: "A spotted big cat of the rainforest" },
        { a: "SNAKE", c: "A long animal with no legs that slithers" },
        { a: "TOUCAN", c: "A bird with a huge colorful beak" },
        { a: "JUNGLE", c: "A thick, wild forest full of animals" },
        { a: "GORILLA", c: "The largest ape, strong and gentle" },
        { a: "LEOPARD", c: "A spotted cat that hides in trees" },
        { a: "PANTHER", c: "A sleek black big cat" },
        { a: "INSECT", c: "A small animal with six legs" },
        { a: "CHEETAH", c: "The fastest land animal" },
      ],
      tricky: [
        { a: "ELEPHANT", c: "A huge gray animal with a long trunk" },
        { a: "CROCODILE", c: "A scaly reptile with a snappy, toothy grin" },
        { a: "BUTTERFLY", c: "A bug with big colorful wings" },
        { a: "RAINFOREST", c: "A warm, wet forest where it rains a lot" },
        { a: "CHIMPANZEE", c: "A clever ape that is one of our closest relatives" },
        { a: "RHINOCEROS", c: "A big animal with a horn on its nose" },
        { a: "HIPPOPOTAMUS", c: "A huge animal that loves wallowing in the river" },
        { a: "ORANGUTAN", c: "A red-haired ape that lives in the trees" },
        { a: "PREDATOR", c: "An animal that hunts other animals for food" },
        { a: "EXPLORER", c: "A person who travels to discover new places" },
        { a: "CAMOUFLAGE", c: "Colors that help an animal blend in and hide" },
        { a: "STAMPEDE", c: "A wild herd running all at once" },
      ],
    },
  },
};

// Friendly difficulty labels used by the UI.
const DIFFICULTIES = [
  { id: "easy", label: "Easy", stars: "⭐", words: 7 },
  { id: "medium", label: "Medium", stars: "⭐⭐", words: 8 },
  { id: "tricky", label: "Tricky", stars: "⭐⭐⭐", words: 9 },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { THEMES, DIFFICULTIES };
}
